{
    "name": "POS Sale Session Report",
    "version": "14.1.1",
    "description":"POS Sale Session Report Odoo with thermal printer",
    "author" : "COONDEV SAS",
    'sequence': 1,
    "email": 'soporte@coondev.com.co',
    "website":'https://coondev.odoo.com/',
    "license": 'OPL-1',
    "category":"Point of Sale",
    "depends": [
        "sale",
    ],
    "data": [
        'views/account_journal.xml',
        'security/ir.model.access.csv',
        'data/cron_crear_sessiones.xml',
        'views/res_partner.xml',
        'views/account_move.xml',
        'views/pos_sale_session.xml',
        'views/point_sale.xml',
        'views/pos_session_report_template.xml',
        'views/pos_session_x_report_template.xml',
        'views/report.xml',
    ],
    'qweb': [],
    'css': [],
    'js': [],
    'images': ['static/description/main_screenshot.png'],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
